-- Sliding window counter - EXERCISE 4 (see docs/curriculum.md).
--
-- KEYS[1]  key for this client/rule
-- ARGV[1]  rate       max requests per trailing period
-- ARGV[2]  period_ms  window length in milliseconds
--
-- Must return { allowed, limit, remaining, retry_after_ms, reset_after_ms }
-- as integers.
--
-- Port your memory.SlidingCounter here: a hash holding the current window
-- index, the current count and the previous count. Two things to think about
-- that the in-memory version let you ignore:
--
--   * TTL: the previous window is only meaningful for one more period after
--     the current one ends. Expire accordingly.
--   * Should the sliding LOG variant exist in Redis too? It maps naturally on
--     to a sorted set (ZADD now, ZREMRANGEBYSCORE up to the cutoff, ZCARD).
--     Implementing it is an optional stretch goal; think about what it costs
--     per key in memory compared to this version, then measure.

return redis.error_reply('NOT_IMPLEMENTED')
